# plasma Makefile

TOP = ..

PSRCS = flux_tube_solver.f90               \
        get_pvalue_dipole.f90              \
        get_sinim.f90                      \
        get_sza.f90                        \
        interpolate_flux_tube.f90          \
        io_plasma_bin.f90                  \
        module_find_neighbor_grid_R.f90    \
        module_find_neighbor_grid_th.f90   \
        module_heating_rate.f90            \
        module_perpendicular_transport.f90 \
        module_plasma.f90                  \
        module_Qinterpolation.f90          \
        module_stepback_mag_R.f90          \
        module_stepback_mag_th.f90         \
        module_sub_plasma.f90              \
        read_vexb.f90

include $(TOP)/Makefile.common
