#!/bin/bash

fail() { echo -e "\n$1\n" && exit 1; }

p=$(readlink -e $0)
d=$(dirname     $p)
b=$(basename    $p)

engine=jruby # 'jruby' or 'ruby'

test -z "$engine" && fail "No engine specified"

if [[ "$engine" = "jruby" ]]
then
  jruby=$d/jruby-complete.jar
  test -f "$jruby" || fail "Cannot find $jruby"
  engine="java -jar $jruby --1.9"
fi

export DDTSHOME=$d

ulimit -St unlimited -Su unlimited && $engine $d/ts.rb $b "$@"
