# eldyn Makefile

TOP = ..

PSRCS = get_efield90km.f           \
        module_cal_monthday.f      \
        module_efield_init.f       \
        module_eldyn.f             \
        module_init_eldyn.f        \
        module_read_acoef.f        \
        module_sub_eldyn.f

SSRCS = apex_sunloc.f              \
        efield.f                   \
        module_adj_S_a.f           \
        module_ADJUST.f            \
        module_bnd_sinus.f         \
        module_constants.f         \
        module_DerivPotential.f    \
        module_efield_mid.f        \
        module_efield_sunloc.f     \
        module_EpotVal.f           \
        module_ff.f                \
        module_FSVal.f             \
        module_fun_MagLong.f       \
        module_fun_MLT.f           \
        module_GECMP.f             \
        module_get_efield.f        \
        module_GET_TILT.f          \
        module_GlobalElPotential.f \
        module_highlat_adjust.f    \
        module_highlat_getbnd.f    \
        module_index_quiet.f       \
        module_interp_poten.f      \
        module_JULDAY.f            \
        module_LEGENDRE.f          \
        module_magfield.f          \
        module_pnm.f               \
        module_pot_latsmo.f        \
        module_pot_latsmo2.f       \
        module_pot_lonsmo.f        \
        module_prep_fk.f           \
        module_prep_pnm.f          \
        module_prep_weimer.f       \
        module_ReadCoef.f          \
        module_set_fkflfs.f        \
        module_SetModel.f          \
        module_sunloc.f            \
        module_svbksb.f            \
        module_svdcmp.f            \
        supim_exb.f

include $(TOP)/Makefile.common
