      integer gptlinitialize
      integer gptlstart
      integer gptlstop
      integer gptlget_nregions
      integer gptlget_regionname
      integer gptlget_wallclock
      integer gptlpr
      integer gptlprint_memusage
      integer gptlget_memusage

      external gptlinitialize
      external gptlstart
      external gptlstop
      external gptlget_nregions
      external gptlget_regionname
      external gptlget_wallclock
      external gptlpr
      external gptlprint_memusage
      external gptlget_memusage

      external gptlprocess_namelist
