#!/bin/csh
set compute_tasks = 1
set RUNDATE = 20170214
set i = 2
echo "RUNDATE=" $RUNDATE
set WORKDIR = /scratch3/BMC/gsd-hpcs/Jacques.Middlecoff/IPEr504
set machine = theia
echo "machine" $machine
set compiler = intel/16.1.150
echo "compiler" $compiler
if ( $compute_tasks == "S" ) then
  set parallelism = serial
else 
  set parallelism = parallel
endif
echo "parallelism" $parallelism
#
    cd $WORKDIR/src
    pwd
    module load $compiler netcdf
    set makejobs = 1
    echo "start compiling..."
    env MAKEJOBS=${makejobs}  make ${machine}_${compiler}_${parallelism} 
    if ( $compute_tasks != "S" ) then
      cp  eldyn/cons_module_sms.f.tmp  eldyn/cons_sms.f.tmp
      make ${machine}_${compiler}_${parallelism} >& mop
    endif
    ###make theia_intel_serial 
    if ( $? != 0 ) then
	echo "exit status" $?
	    echo "error STOP! compiling failed!"
		exit 1
    endif

