#!/bin/csh
#
if ( $#argv == 0) then
  set par = "serial"
# Need at least 2 compute tasks to provide enough memory.
  set compute_tasks = 2
  set name = ipe_S
else 
  set par = "parallel"
  set compute_tasks = $1
  set name = ipe_${compute_tasks}
endif
set  rundir = "${name}_${$}"
mkdir $rundir
echo Created $rundir
cd  $rundir
cp ../../bin/ipe_v18.ifort.exe .
cp ../coef*                    .
cp ../GPTLnamelist             .
cp ../SMSnamelist              .
cp ../IPE.inp                  .
cp ../wei96.cofcnts            .
cp ../stup_ut_rec              .
cp ../qsubipeJet               .
cp ../load_balance_groups1     .
ln -s /pan2/projects/fim-njet/jacques/IPEdata/* .

# Make rundir a full path for runscript
set rundir = $cwd

cat << EOF >! runscript
#!/bin/csh
  cd $rundir
  pwd
  limit
  module purge
  module load intel
  cat /proc/cpuinfo
  if ($par == 'parallel') then
    module load mvapich2
    set cmd = "time mpiexec -np $compute_tasks ./ipe_v18.ifort.exe"
  else
    set cmd = "time ./ipe_v18.ifort.exe"
  endif
  module list
  echo "running \$cmd" > output
  (\$cmd) >> output

if (\$status != 0) then
  echo ipe failed
  exit 23
else
  echo ipe finished
endif
exit 0
EOF

chmod 755 ./runscript
set queue_time=00:30:00

qsub -N $name \
     -A acb-gpu \
     -q batch \
     -l partition=sjet \
#    -l partition=tgpu \
#    -l nodes=1:ppn=2 \
     -l procs=$compute_tasks \
     -l walltime=$queue_time \
     ./runscript || echo "qsub failed" && exit 1

exit 0


