#!/bin/csh
# ./script 
###<1:d or b> <2:compute_tasks> <3:IPETIME> <4:IPEDATA: full path>  <5:sw_compile> <6:RUNDATE>  <7:imax> 
set sw_compile = 1
#set compute_tasks = S
set compute_tasks = 2
set RUNDATE = 20170214
set i = 2
echo "RUNDATE=" $RUNDATE
set WORKDIR = /scratch3/BMC/gsd-hpcs/Jacques.Middlecoff/IPEr493
set machine = theia
echo "machine" $machine
set compiler = intel
echo "compiler" $compiler
if ( $compute_tasks == "S" ) then
  set parallelism = serial
else 
  set parallelism = parallel
endif
echo "parallelism" $parallelism
#
### over-write the setting inside qsubipe:
setenv IPEQUEUE  "debug" 
setenv IPETIME  00:30:00
#
cd $WORKDIR/run
pwd
if ( $compute_tasks == "S" ) then
  ./qsubipe ${machine} ${compiler} ${parallelism}                  > jid$RUNDATE$i
else 
  ./qsubipe ${machine} ${compiler} ${parallelism} ${compute_tasks} > jid$RUNDATE$i
endif

