#!/bin/csh
set compute_tasks = 35
set RUNDATE = 20170214
set i = 2
echo "RUNDATE=" $RUNDATE
set WORKDIR = /scratch3/BMC/gsd-hpcs/Jacques.Middlecoff/IPEr504
set machine = theia
echo "machine" $machine
set compiler = intel/16.1.150
echo "compiler" $compiler
if ( $compute_tasks == "S" ) then
  set parallelism = serial
else 
  set parallelism = parallel
endif
echo "parallelism" $parallelism
#
### over-write the setting inside qsubipe:
setenv IPEQUEUE  "debug" 
setenv IPETIME  00:30:00
#
cd $WORKDIR/run
pwd
if ( $compute_tasks == "S" ) then
  ./qsubipe ${machine} ${compiler} ${parallelism}                 
else 
  ./qsubipe ${machine} ${compiler} ${parallelism} ${compute_tasks}
endif

