# Makefile for NIM dynamics compiled using SMS

SHELL = /bin/sh

all: $(OBJ)

#.SILENT:
.SUFFIXES:
.SUFFIXES: .o .f90 .f

.f90.o  :
	echo group1
	$(PPP) $(PPP_FLAGS) $*.f90 
	mv $*_sms.f $*_sms.f90
	$(FC) -c $(FFLAGS) $(MODDIRS) $(SMSFLAGS) $*_sms.f90
	mv $*_sms.o $*.o

module_decomp.o: module_decomp.f90
	echo group2
	$(PPP) $(PPP_FLAGS1) $*.f90 
	mv $*_sms.f $*_sms.f90
	$(FC) -c $(FFLAGS) $(MODDIRS) $(SMSFLAGS) $*_sms.f90
	mv $*_sms.o $*.o
