#SHELL=/bin/bash
all: $(OBJ)

# Optimized compilations
xyz.o: xyz.f
	$(FC) -c $(FFLAGS) xyz.f

### rules ###

.SUFFIXES:
.SUFFIXES: .o .c .cc .f .FOR .for .f90 .mod .F
#
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
.cc.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@
.f.o:
	$(FC) $(FFLAGS) -c $< -o $@
.FOR.o:
	$(FC) $(FFLAGS) -c $< -o $@
.f90.mod:
	echo mod $(FC) $(FFLAGS90)
	$(FC) $(FFLAGS90) -c $< -o $@
.f90.o:
	$(FC) $(FFLAGS90) -c $< -o $@
.F.o:
	$(FC) $(FFLAGS_F) -c $< -o $@
