#!/bin/bash

unknown() {
  echo "Unknown compiler '$2' for machine '$1'."
  exit 1
}

usage() {
  echo "USAGE: $(basename $0) <machine> <compiler>"
  exit 1
}

test -z "$1" -o -z "$2" && usage

case $1 in
  "trillian")
    case $2 in
      "cray")
        echo "source /opt/modules/default/init/sh && module purge && module load PrgEnv-cray cray-mpich2 xpmem dmapp ugni udreg"
        ;;
      "pgi")
        echo "source /opt/modules/default/init/sh && module purge && module load PrgEnv-pgi cray-mpich2 xpmem dmapp ugni udreg"
        ;;
      *) unknown $1 $2
        ;;
    esac
    ;;
  "zeus")
    case $2 in
      "intel")
        echo "source /usr/share/Modules/init/sh && module purge && module load intel mpt"
        ;;
      "lahey")
        echo "source /usr/share/Modules/init/sh && module purge && module load lahey mpt"
        ;;
      *) unknown $1 $2
        ;;
    esac
    ;;
esac
